using System.Text;
using LLama;
using LLama.Common;
using LLama.Sampling;

namespace QuestResume.Core.Rag;

/// <summary>
/// Wraps a local GGUF model loaded via LLamaSharp (llama.cpp), running entirely on CPU
/// in-process. No network access and no per-token cost.
/// </summary>
public sealed class LocalLlmService : IDisposable
{
    private readonly LLamaWeights _weights;
    private readonly ModelParams _modelParams;
    private readonly LlmSamplingOptions _sampling;

    private LocalLlmService(LLamaWeights weights, ModelParams modelParams, LlmSamplingOptions sampling)
    {
        _weights = weights;
        _modelParams = modelParams;
        _sampling = sampling;
    }

    /// <summary>
    /// Loads the model at <paramref name="modelPath"/>. Throws <see cref="ModelNotConfiguredException"/>
    /// if the path is empty or the file doesn't exist.
    /// </summary>
    public static LocalLlmService Load(string modelPath, int contextSize = 4096, int gpuLayerCount = 0, LlmSamplingOptions? sampling = null)
    {
        if (string.IsNullOrWhiteSpace(modelPath) || !File.Exists(modelPath))
        {
            throw new ModelNotConfiguredException(modelPath);
        }

        var modelParams = new ModelParams(modelPath)
        {
            ContextSize = (uint)contextSize,
            GpuLayerCount = gpuLayerCount
        };

        var weights = LLamaWeights.LoadFromFile(modelParams);
        return new LocalLlmService(weights, modelParams, sampling ?? LlmSamplingOptions.Default);
    }

    /// <summary>
    /// Runs a single-shot, stateless completion for <paramref name="prompt"/>.
    /// </summary>
    public async Task<string> AskAsync(string prompt, CancellationToken cancellationToken = default)
    {
        var builder = new StringBuilder();
        await foreach (var token in AskStreamAsync(prompt, cancellationToken).ConfigureAwait(false))
        {
            builder.Append(token);
        }

        return builder.ToString().Trim();
    }

    /// <summary>
    /// Runs a single-shot, stateless completion for <paramref name="prompt"/>, yielding each
    /// token as it's generated by llama.cpp's <see cref="StatelessExecutor"/>.
    /// </summary>
    public IAsyncEnumerable<string> AskStreamAsync(string prompt, CancellationToken cancellationToken = default)
    {
        var executor = new StatelessExecutor(_weights, _modelParams);

        var samplingPipeline = new DefaultSamplingPipeline
        {
            Temperature = (float)_sampling.Temperature,
            TopP = (float)_sampling.TopP
        };
        if (_sampling.Seed is int seed)
        {
            samplingPipeline.Seed = (uint)seed;
        }

        var inferenceParams = new InferenceParams
        {
            MaxTokens = 512,
            AntiPrompts = new List<string> { "PERGUNTA_DO_USUARIO:", "<documento" },
            SamplingPipeline = samplingPipeline
        };

        return executor.InferAsync(prompt, inferenceParams, cancellationToken);
    }

    public void Dispose()
    {
        _weights.Dispose();
    }
}
